FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME HR
ENV MONGODB_CLUSTER_ADDRESS hr.jdtf367.mongodb.net
ENV MONGODB_USERNAME pakiozihak
ENV MONGODB_PASSWORD vboNS4XCkUD14wZi

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]

